# Generated by Django 5.0.4 on 2025-05-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DokumenHukum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=100, verbose_name='Nomor Dokumen')),
                ('judul', models.TextField(verbose_name='Judul')),
                ('tahun', models.PositiveIntegerField(verbose_name='Tahun Terbit')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditetapkan')),
                ('file_pdf', models.FileField(upload_to='dokumen/', verbose_name='File Dokumen')),
                ('isi_teks', models.TextField(blank=True, help_text='Teks hasil ekstrak dari file PDF', verbose_name='Isi Teks')),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='Jdih.jenisdokumen')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jdih.kategoridokumen')),
            ],
            options={
                'ordering': ['-tahun', 'judul'],
            },
        ),
    ]
