# Generated by Django 5.0.4 on 2025-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumenhukum',
            name='jenis',
        ),
        migrations.DeleteModel(
            name='JenisDokumen',
        ),
    ]
