# Generated by Django 5.0.4 on 2025-05-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0002_remove_dokumenhukum_jenis_delete_jenisdokumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('pesan', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dokumenhukum',
            name='file_pdf',
            field=models.FileField(upload_to='', verbose_name='File Dokumen'),
        ),
        migrations.AlterField(
            model_name='dokumenhukum',
            name='isi_teks',
            field=models.TextField(blank=True, help_text='Teks ekstrak dari PDF', verbose_name='Isi Teks'),
        ),
    ]
