# Generated by Django 5.0.4 on 2025-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0003_kontak_alter_dokumenhukum_file_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoridokumen',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
