# Generated by Django 5.0.4 on 2025-06-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0004_kategoridokumen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenhukum',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
