# Generated by Django 5.0.4 on 2025-06-19 03:50

from django.db import migrations
from django.utils.text import slugify
from Jdih.models import DokumenHukum

def generate_slugs(apps, schema_editor):
    DokumenHukum = apps.get_model('Jdih', 'DokumenHukum')
    for dokumen in DokumenHukum.objects.all():
        if not dokumen.slug:
            base_slug = slugify(dokumen.judul)[:200]
            unique_slug = base_slug
            counter = 1
            while DokumenHukum.objects.filter(slug=unique_slug).exclude(pk=dokumen.pk).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            dokumen.slug = unique_slug
            dokumen.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0005_dokumenhukum_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs)
    ]
