# Generated by Django 5.0.4 on 2025-06-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0006_populate_dokumen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenhukum',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
