# Generated by Django 5.0.4 on 2025-06-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0007_alter_dokumenhukum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenhukum',
            name='file_pdf',
            field=models.FileField(upload_to='dokumen_hukum', verbose_name='File Dokumen'),
        ),
    ]
