# Generated by Django 5.0.4 on 2025-06-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0009_alter_dokumenhukum_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenhukum',
            name='tanggal_ditetapkan',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Ditetapkan'),
        ),
    ]
