# Generated by Django 5.0.4 on 2025-06-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0010_alter_dokumenhukum_tanggal_ditetapkan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenhukum',
            name='slug',
            field=models.SlugField(blank=True, max_length=225, unique=True),
        ),
    ]
