# Generated by Django 5.0.4 on 2025-06-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0011_alter_dokumenhukum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenhukum',
            name='file_pdf',
            field=models.FileField(max_length=225, upload_to='dokumen_hukum/', verbose_name='File Dokumen'),
        ),
    ]
