# Generated by Django 5.2.5 on 2025-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jdih', '0012_alter_dokumenhukum_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenhukum',
            name='jumlah_dilihat',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='dokumenhukum',
            name='jumlah_diunduh',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
